--
-- PostgreSQL database dump
--

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    account_id character varying(255) NOT NULL,
    account_type character varying(255) NOT NULL,
    balance numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['SAVINGS'::character varying, 'CHECKING'::character varying, 'BUSINESS'::character varying])::text[]))),
    CONSTRAINT accounts_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'BLOCKED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    last_login_at timestamp(6) without time zone,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    locked_until timestamp(6) without time zone,
    CONSTRAINT app_users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'ANALYST'::character varying, 'INVESTIGATOR'::character varying, 'VIEWER'::character varying, 'TESTER'::character varying])::text[]))),
    CONSTRAINT app_users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DISABLED'::character varying, 'LOCKED'::character varying])::text[])))
);


--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    entity_id character varying(255) NOT NULL,
    entity_type character varying(255) NOT NULL,
    event_type character varying(255) NOT NULL,
    new_value oid,
    old_value oid,
    role character varying(255),
    username character varying(255) NOT NULL,
    CONSTRAINT audit_logs_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['CUSTOMER_CREATED'::character varying, 'ACCOUNT_CREATED'::character varying, 'TRANSACTION_CREATED'::character varying, 'RISK_SCORE_GENERATED'::character varying, 'FRAUD_ALERT_CREATED'::character varying, 'ALERT_STATUS_UPDATED'::character varying, 'CASE_CREATED'::character varying, 'CASE_UPDATED'::character varying, 'CASE_DECISION_UPDATED'::character varying, 'DATA_INGESTION_STARTED'::character varying, 'DATA_INGESTION_COMPLETED'::character varying, 'DATA_QUALITY_CHECK_COMPLETED'::character varying, 'PIPELINE_FAILED'::character varying, 'ML_SCORE_REQUESTED'::character varying, 'ML_SCORE_COMPLETED'::character varying, 'ML_SCORE_FAILED'::character varying, 'USER_CREATED'::character varying, 'USER_UPDATED'::character varying, 'USER_DISABLED'::character varying, 'USER_PASSWORD_RESET'::character varying, 'LOGIN_SUCCESS'::character varying, 'LOGIN_FAILED'::character varying, 'TEST_TRANSACTION_CREATED'::character varying, 'TEST_TRANSACTION_RISK_SCORED'::character varying, 'TEST_TRANSACTION_ALERT_GENERATED'::character varying])::text[])))
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: banking_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.banking_transactions (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    channel character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(255) NOT NULL,
    device_id character varying(255),
    ip_address character varying(255),
    merchant_category character varying(255),
    status character varying(255) NOT NULL,
    transaction_id character varying(255) NOT NULL,
    transaction_type character varying(255) NOT NULL,
    customer_id bigint NOT NULL,
    destination_account_id bigint,
    source_account_id bigint NOT NULL,
    CONSTRAINT banking_transactions_channel_check CHECK (((channel)::text = ANY ((ARRAY['MOBILE'::character varying, 'WEB'::character varying, 'ATM'::character varying, 'POS'::character varying, 'BRANCH'::character varying])::text[]))),
    CONSTRAINT banking_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILED'::character varying, 'PENDING'::character varying, 'REVERSED'::character varying])::text[]))),
    CONSTRAINT banking_transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['TRANSFER'::character varying, 'WITHDRAWAL'::character varying, 'DEPOSIT'::character varying, 'PAYMENT'::character varying, 'CARD_PAYMENT'::character varying])::text[])))
);


--
-- Name: banking_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.banking_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banking_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clean_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clean_transactions (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    channel character varying(255) NOT NULL,
    country character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(255) NOT NULL,
    customer_id character varying(255) NOT NULL,
    destination_account_id character varying(255),
    device_id character varying(255),
    ip_address character varying(255),
    loaded_at timestamp(6) without time zone NOT NULL,
    merchant_category character varying(255),
    source_account_id character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    transaction_id character varying(255) NOT NULL,
    transaction_type character varying(255) NOT NULL,
    ingestion_run_id bigint NOT NULL,
    CONSTRAINT clean_transactions_channel_check CHECK (((channel)::text = ANY ((ARRAY['MOBILE'::character varying, 'WEB'::character varying, 'ATM'::character varying, 'POS'::character varying, 'BRANCH'::character varying])::text[]))),
    CONSTRAINT clean_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILED'::character varying, 'PENDING'::character varying, 'REVERSED'::character varying])::text[]))),
    CONSTRAINT clean_transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['TRANSFER'::character varying, 'WITHDRAWAL'::character varying, 'DEPOSIT'::character varying, 'PAYMENT'::character varying, 'CARD_PAYMENT'::character varying])::text[])))
);


--
-- Name: clean_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clean_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clean_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    country character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_id character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    phone character varying(255),
    risk_level character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT customers_risk_level_check CHECK (((risk_level)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT customers_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: data_quality_issue_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_quality_issue_details (
    id bigint NOT NULL,
    detected_at timestamp(6) without time zone NOT NULL,
    issue_description oid NOT NULL,
    record_identifier character varying(255),
    data_quality_result_id bigint NOT NULL
);


--
-- Name: data_quality_issue_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.data_quality_issue_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_quality_issue_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: data_quality_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_quality_results (
    id bigint NOT NULL,
    check_name character varying(255) NOT NULL,
    passed boolean NOT NULL,
    records_checked integer NOT NULL,
    records_failed integer NOT NULL,
    records_passed integer NOT NULL,
    data_quality_run_id bigint NOT NULL
);


--
-- Name: data_quality_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.data_quality_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_quality_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: data_quality_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.data_quality_runs (
    id bigint NOT NULL,
    finished_at timestamp(6) without time zone,
    run_id character varying(255) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    total_issues_found integer NOT NULL,
    total_records_checked integer NOT NULL,
    triggered_by character varying(255),
    pipeline_run_id bigint,
    CONSTRAINT data_quality_runs_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'SUCCESS'::character varying, 'PARTIAL_SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: data_quality_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.data_quality_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_quality_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dead_letter_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dead_letter_transactions (
    id bigint NOT NULL,
    error_reason oid NOT NULL,
    error_type character varying(255) NOT NULL,
    event_id character varying(255) NOT NULL,
    last_retry_at timestamp(6) without time zone,
    processed_status character varying(255) NOT NULL,
    raw_payload oid NOT NULL,
    received_at timestamp(6) without time zone NOT NULL,
    ingestion_run_id bigint,
    CONSTRAINT dead_letter_transactions_processed_status_check CHECK (((processed_status)::text = ANY ((ARRAY['NEW'::character varying, 'RETRIED'::character varying, 'IGNORED'::character varying, 'RESOLVED'::character varying])::text[])))
);


--
-- Name: dead_letter_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dead_letter_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dead_letter_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fraud_alerts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fraud_alerts (
    id bigint NOT NULL,
    alert_id character varying(255) NOT NULL,
    alert_type character varying(255) NOT NULL,
    assigned_to character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    message text NOT NULL,
    priority character varying(255) NOT NULL,
    resolved_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    customer_id bigint NOT NULL,
    risk_score_id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    CONSTRAINT fraud_alerts_alert_type_check CHECK (((alert_type)::text = ANY ((ARRAY['RULE_BASED'::character varying, 'ML_ANOMALY'::character varying, 'HYBRID'::character varying])::text[]))),
    CONSTRAINT fraud_alerts_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT fraud_alerts_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'ACKNOWLEDGED'::character varying, 'INVESTIGATING'::character varying, 'FALSE_POSITIVE'::character varying, 'CONFIRMED_FRAUD'::character varying, 'RESOLVED'::character varying, 'ESCALATED'::character varying])::text[])))
);


--
-- Name: fraud_alerts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fraud_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fraud_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: id_sequence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.id_sequence (
    prefix character varying(255) NOT NULL,
    last_value bigint NOT NULL
);


--
-- Name: ingestion_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingestion_runs (
    id bigint NOT NULL,
    accepted_rows integer NOT NULL,
    dead_letter_rows integer NOT NULL,
    file_name character varying(255) NOT NULL,
    finished_at timestamp(6) without time zone,
    rejected_rows integer NOT NULL,
    run_id character varying(255) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    total_rows integer NOT NULL,
    pipeline_run_id bigint,
    CONSTRAINT ingestion_runs_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'SUCCESS'::character varying, 'PARTIAL_SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: ingestion_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingestion_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingestion_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: investigation_cases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.investigation_cases (
    id bigint NOT NULL,
    assigned_to character varying(255),
    case_id character varying(255) NOT NULL,
    closed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    decision character varying(255) NOT NULL,
    notes oid,
    priority character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    alert_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    CONSTRAINT investigation_cases_decision_check CHECK (((decision)::text = ANY ((ARRAY['PENDING'::character varying, 'FALSE_POSITIVE'::character varying, 'CONFIRMED_FRAUD'::character varying, 'NEEDS_MORE_REVIEW'::character varying])::text[]))),
    CONSTRAINT investigation_cases_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT investigation_cases_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_REVIEW'::character varying, 'ESCALATED'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: investigation_cases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.investigation_cases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investigation_cases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pipeline_errors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pipeline_errors (
    id bigint NOT NULL,
    error_message oid NOT NULL,
    error_type character varying(255) NOT NULL,
    occurred_at timestamp(6) without time zone NOT NULL,
    pipeline_run_id bigint NOT NULL,
    pipeline_task_run_id bigint
);


--
-- Name: pipeline_errors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pipeline_errors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pipeline_errors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pipeline_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pipeline_runs (
    id bigint NOT NULL,
    duration_ms bigint,
    failure_reason character varying(255),
    finished_at timestamp(6) without time zone,
    pipeline_type character varying(255) NOT NULL,
    records_accepted integer NOT NULL,
    records_failed integer NOT NULL,
    records_processed integer NOT NULL,
    records_rejected integer NOT NULL,
    run_id character varying(255) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    triggered_by character varying(255),
    CONSTRAINT pipeline_runs_pipeline_type_check CHECK (((pipeline_type)::text = ANY ((ARRAY['INGESTION'::character varying, 'DATA_QUALITY'::character varying])::text[]))),
    CONSTRAINT pipeline_runs_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'SUCCESS'::character varying, 'PARTIAL_SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: pipeline_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pipeline_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pipeline_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pipeline_task_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pipeline_task_runs (
    id bigint NOT NULL,
    error_message oid,
    finished_at timestamp(6) without time zone,
    records_processed integer NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    task_name character varying(255) NOT NULL,
    pipeline_run_id bigint NOT NULL,
    CONSTRAINT pipeline_task_runs_status_check CHECK (((status)::text = ANY ((ARRAY['RUNNING'::character varying, 'SUCCESS'::character varying, 'PARTIAL_SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: pipeline_task_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pipeline_task_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pipeline_task_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raw_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.raw_transactions (
    id bigint NOT NULL,
    amount_raw character varying(255),
    channel_raw character varying(255),
    country_raw character varying(255),
    created_at_raw character varying(255),
    currency_raw character varying(255),
    customer_id_raw character varying(255),
    destination_account_id_raw character varying(255),
    device_id_raw character varying(255),
    ingested_at timestamp(6) without time zone NOT NULL,
    ip_address_raw character varying(255),
    merchant_category_raw character varying(255),
    raw_line oid NOT NULL,
    row_number integer NOT NULL,
    source_account_id_raw character varying(255),
    status_raw character varying(255),
    transaction_id_raw character varying(255),
    transaction_type_raw character varying(255),
    ingestion_run_id bigint NOT NULL
);


--
-- Name: raw_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.raw_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.raw_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rejected_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rejected_transactions (
    id bigint NOT NULL,
    reason character varying(255) NOT NULL,
    reason_detail oid NOT NULL,
    rejected_at timestamp(6) without time zone NOT NULL,
    ingestion_run_id bigint NOT NULL,
    staging_transaction_id bigint NOT NULL,
    CONSTRAINT rejected_transactions_reason_check CHECK (((reason)::text = ANY ((ARRAY['MISSING_REQUIRED_FIELD'::character varying, 'INVALID_AMOUNT'::character varying, 'INVALID_TRANSACTION_TYPE'::character varying, 'INVALID_CHANNEL'::character varying, 'INVALID_STATUS'::character varying, 'UNKNOWN_CUSTOMER'::character varying, 'UNKNOWN_ACCOUNT'::character varying, 'DUPLICATE_TRANSACTION_ID'::character varying, 'FUTURE_CREATED_AT'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: rejected_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rejected_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rejected_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: risk_scores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.risk_scores (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    explanation oid,
    final_score integer NOT NULL,
    ml_score integer,
    risk_level character varying(255) NOT NULL,
    rule_score integer NOT NULL,
    triggered_rules oid,
    transaction_id bigint NOT NULL,
    ml_explanation oid,
    scoring_source character varying(255) NOT NULL,
    CONSTRAINT risk_scores_risk_level_check CHECK (((risk_level)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT risk_scores_scoring_source_check CHECK (((scoring_source)::text = ANY ((ARRAY['HYBRID'::character varying, 'RULE_ONLY'::character varying])::text[])))
);


--
-- Name: risk_scores_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.risk_scores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.risk_scores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staging_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.staging_transactions (
    id bigint NOT NULL,
    amount numeric(38,2),
    channel character varying(255),
    country character varying(255),
    created_at timestamp(6) without time zone,
    currency character varying(255),
    customer_id character varying(255),
    destination_account_id character varying(255),
    device_id character varying(255),
    ip_address character varying(255),
    merchant_category character varying(255),
    parse_errors oid,
    source_account_id character varying(255),
    staged_at timestamp(6) without time zone NOT NULL,
    status character varying(255),
    transaction_id character varying(255),
    transaction_type character varying(255),
    ingestion_run_id bigint NOT NULL,
    raw_transaction_id bigint NOT NULL
);


--
-- Name: staging_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.staging_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staging_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: banking_transactions banking_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banking_transactions
    ADD CONSTRAINT banking_transactions_pkey PRIMARY KEY (id);


--
-- Name: clean_transactions clean_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clean_transactions
    ADD CONSTRAINT clean_transactions_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: data_quality_issue_details data_quality_issue_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_quality_issue_details
    ADD CONSTRAINT data_quality_issue_details_pkey PRIMARY KEY (id);


--
-- Name: data_quality_results data_quality_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_quality_results
    ADD CONSTRAINT data_quality_results_pkey PRIMARY KEY (id);


--
-- Name: data_quality_runs data_quality_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_quality_runs
    ADD CONSTRAINT data_quality_runs_pkey PRIMARY KEY (id);


--
-- Name: dead_letter_transactions dead_letter_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dead_letter_transactions
    ADD CONSTRAINT dead_letter_transactions_pkey PRIMARY KEY (id);


--
-- Name: fraud_alerts fraud_alerts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT fraud_alerts_pkey PRIMARY KEY (id);


--
-- Name: id_sequence id_sequence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.id_sequence
    ADD CONSTRAINT id_sequence_pkey PRIMARY KEY (prefix);


--
-- Name: ingestion_runs ingestion_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingestion_runs
    ADD CONSTRAINT ingestion_runs_pkey PRIMARY KEY (id);


--
-- Name: investigation_cases investigation_cases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investigation_cases
    ADD CONSTRAINT investigation_cases_pkey PRIMARY KEY (id);


--
-- Name: pipeline_errors pipeline_errors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipeline_errors
    ADD CONSTRAINT pipeline_errors_pkey PRIMARY KEY (id);


--
-- Name: pipeline_runs pipeline_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipeline_runs
    ADD CONSTRAINT pipeline_runs_pkey PRIMARY KEY (id);


--
-- Name: pipeline_task_runs pipeline_task_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipeline_task_runs
    ADD CONSTRAINT pipeline_task_runs_pkey PRIMARY KEY (id);


--
-- Name: raw_transactions raw_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_transactions
    ADD CONSTRAINT raw_transactions_pkey PRIMARY KEY (id);


--
-- Name: rejected_transactions rejected_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rejected_transactions
    ADD CONSTRAINT rejected_transactions_pkey PRIMARY KEY (id);


--
-- Name: risk_scores risk_scores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_scores
    ADD CONSTRAINT risk_scores_pkey PRIMARY KEY (id);


--
-- Name: staging_transactions staging_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staging_transactions
    ADD CONSTRAINT staging_transactions_pkey PRIMARY KEY (id);


--
-- Name: risk_scores uk2jdg26jvs20sjh53je9u45lth; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_scores
    ADD CONSTRAINT uk2jdg26jvs20sjh53je9u45lth UNIQUE (transaction_id);


--
-- Name: app_users uk4vj92ux8a2eehds1mdvmks473; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT uk4vj92ux8a2eehds1mdvmks473 UNIQUE (email);


--
-- Name: investigation_cases uk7d2rajp3ehg11enlssrbc81us; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investigation_cases
    ADD CONSTRAINT uk7d2rajp3ehg11enlssrbc81us UNIQUE (case_id);


--
-- Name: staging_transactions uk7gs5a4i6wsuqom41phq06vak4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staging_transactions
    ADD CONSTRAINT uk7gs5a4i6wsuqom41phq06vak4 UNIQUE (raw_transaction_id);


--
-- Name: pipeline_runs uk8co08raw669meale7luks1e32; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipeline_runs
    ADD CONSTRAINT uk8co08raw669meale7luks1e32 UNIQUE (run_id);


--
-- Name: ingestion_runs uka3x651akrfki9by8rqm1w1ymh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingestion_runs
    ADD CONSTRAINT uka3x651akrfki9by8rqm1w1ymh UNIQUE (pipeline_run_id);


--
-- Name: accounts ukc662f7lm5ec167m89rp50kb1d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT ukc662f7lm5ec167m89rp50kb1d UNIQUE (account_id);


--
-- Name: banking_transactions ukcu9pmwo49n0yean10y6xxb63h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banking_transactions
    ADD CONSTRAINT ukcu9pmwo49n0yean10y6xxb63h UNIQUE (transaction_id);


--
-- Name: fraud_alerts ukjnsegie8wf93kg8otup1lrklj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT ukjnsegie8wf93kg8otup1lrklj UNIQUE (risk_score_id);


--
-- Name: rejected_transactions ukjsxkv95rmbakkdndk11sc48jx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rejected_transactions
    ADD CONSTRAINT ukjsxkv95rmbakkdndk11sc48jx UNIQUE (staging_transaction_id);


--
-- Name: data_quality_runs ukk8fkn91grikwqm7c96ey08d2o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_quality_runs
    ADD CONSTRAINT ukk8fkn91grikwqm7c96ey08d2o UNIQUE (pipeline_run_id);


--
-- Name: clean_transactions ukkrwfhqwohssq1xo73qmepbdhj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clean_transactions
    ADD CONSTRAINT ukkrwfhqwohssq1xo73qmepbdhj UNIQUE (transaction_id);


--
-- Name: app_users ukku59eu12sdh7omdic3dx3a2jw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT ukku59eu12sdh7omdic3dx3a2jw UNIQUE (user_id);


--
-- Name: data_quality_runs ukltl4snkqrci2cxye36vtdm5qq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_quality_runs
    ADD CONSTRAINT ukltl4snkqrci2cxye36vtdm5qq UNIQUE (run_id);


--
-- Name: dead_letter_transactions uklysa8b02yw6qwx5katp64ctb1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dead_letter_transactions
    ADD CONSTRAINT uklysa8b02yw6qwx5katp64ctb1 UNIQUE (event_id);


--
-- Name: customers ukn6axkf7qwn8r7s7ce5gso1xpr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukn6axkf7qwn8r7s7ce5gso1xpr UNIQUE (customer_id);


--
-- Name: ingestion_runs uknnv6qrdvncfiue56nfp84j1lj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingestion_runs
    ADD CONSTRAINT uknnv6qrdvncfiue56nfp84j1lj UNIQUE (run_id);


--
-- Name: fraud_alerts uknx4c9g41t4r7xt1rnijhlog36; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT uknx4c9g41t4r7xt1rnijhlog36 UNIQUE (transaction_id);


--
-- Name: fraud_alerts ukq6xnf0a52rkuhoc5wungkh6or; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT ukq6xnf0a52rkuhoc5wungkh6or UNIQUE (alert_id);


--
-- Name: investigation_cases ukqn7sx7a9nkk23doqxrpqvc0gc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investigation_cases
    ADD CONSTRAINT ukqn7sx7a9nkk23doqxrpqvc0gc UNIQUE (alert_id);


--
-- Name: customers ukrfbvkrffamfql7cjmen8v976v; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukrfbvkrffamfql7cjmen8v976v UNIQUE (email);


--
-- Name: app_users ukspsnwr241e9k9c8p5xl4k45ih; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT ukspsnwr241e9k9c8p5xl4k45ih UNIQUE (username);


--
-- Name: banking_transactions fk1ta3mfms7kq21k2he86voqf37; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banking_transactions
    ADD CONSTRAINT fk1ta3mfms7kq21k2he86voqf37 FOREIGN KEY (destination_account_id) REFERENCES public.accounts(id);


--
-- Name: investigation_cases fk49ude6b8xi6shlhrdja013max; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investigation_cases
    ADD CONSTRAINT fk49ude6b8xi6shlhrdja013max FOREIGN KEY (alert_id) REFERENCES public.fraud_alerts(id);


--
-- Name: data_quality_issue_details fk7uysvf33042jg35obvpxcvk2w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_quality_issue_details
    ADD CONSTRAINT fk7uysvf33042jg35obvpxcvk2w FOREIGN KEY (data_quality_result_id) REFERENCES public.data_quality_results(id);


--
-- Name: banking_transactions fk8hnpyjswvmhqab8vklp91b9k5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banking_transactions
    ADD CONSTRAINT fk8hnpyjswvmhqab8vklp91b9k5 FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: pipeline_task_runs fk94v5eg2pc5eaxwvklpr47vqx1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipeline_task_runs
    ADD CONSTRAINT fk94v5eg2pc5eaxwvklpr47vqx1 FOREIGN KEY (pipeline_run_id) REFERENCES public.pipeline_runs(id);


--
-- Name: risk_scores fkam296imtcgetubg7no22tdtk9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.risk_scores
    ADD CONSTRAINT fkam296imtcgetubg7no22tdtk9 FOREIGN KEY (transaction_id) REFERENCES public.banking_transactions(id);


--
-- Name: data_quality_results fkb627d6552hovxgwon43guu89h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_quality_results
    ADD CONSTRAINT fkb627d6552hovxgwon43guu89h FOREIGN KEY (data_quality_run_id) REFERENCES public.data_quality_runs(id);


--
-- Name: banking_transactions fkdamchnf4cd0ruis6oboj5q8wm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.banking_transactions
    ADD CONSTRAINT fkdamchnf4cd0ruis6oboj5q8wm FOREIGN KEY (source_account_id) REFERENCES public.accounts(id);


--
-- Name: raw_transactions fkf132btccwsytmfy8pwaajlp8d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raw_transactions
    ADD CONSTRAINT fkf132btccwsytmfy8pwaajlp8d FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id);


--
-- Name: fraud_alerts fkf29jrjhcw1n5wh0fpibr42imq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT fkf29jrjhcw1n5wh0fpibr42imq FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: clean_transactions fkgsnj8ql2mpr5inij7r28i5u6q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clean_transactions
    ADD CONSTRAINT fkgsnj8ql2mpr5inij7r28i5u6q FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id);


--
-- Name: fraud_alerts fkh33l4drx7phrvnj7k9xrnftv8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT fkh33l4drx7phrvnj7k9xrnftv8 FOREIGN KEY (transaction_id) REFERENCES public.banking_transactions(id);


--
-- Name: ingestion_runs fkhks0foka57y20eyehqp8xuvm1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingestion_runs
    ADD CONSTRAINT fkhks0foka57y20eyehqp8xuvm1 FOREIGN KEY (pipeline_run_id) REFERENCES public.pipeline_runs(id);


--
-- Name: pipeline_errors fkiq56g0ttlcolorcnr5kyccko8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipeline_errors
    ADD CONSTRAINT fkiq56g0ttlcolorcnr5kyccko8 FOREIGN KEY (pipeline_task_run_id) REFERENCES public.pipeline_task_runs(id);


--
-- Name: rejected_transactions fkjhvse989mc95tlauxy4d3c6vg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rejected_transactions
    ADD CONSTRAINT fkjhvse989mc95tlauxy4d3c6vg FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id);


--
-- Name: pipeline_errors fkk2fjlw6ty3nvuwkf8adcc6rf0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipeline_errors
    ADD CONSTRAINT fkk2fjlw6ty3nvuwkf8adcc6rf0 FOREIGN KEY (pipeline_run_id) REFERENCES public.pipeline_runs(id);


--
-- Name: fraud_alerts fkk3q5odw62sy9fgui9yhkd7o8j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_alerts
    ADD CONSTRAINT fkk3q5odw62sy9fgui9yhkd7o8j FOREIGN KEY (risk_score_id) REFERENCES public.risk_scores(id);


--
-- Name: accounts fkn6x8pdp50os8bq5rbb792upse; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fkn6x8pdp50os8bq5rbb792upse FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: staging_transactions fko8qklh2ln6hnn27dbqbw4rgry; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staging_transactions
    ADD CONSTRAINT fko8qklh2ln6hnn27dbqbw4rgry FOREIGN KEY (raw_transaction_id) REFERENCES public.raw_transactions(id);


--
-- Name: data_quality_runs fkskn137mklcyckq004wx39y7nq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.data_quality_runs
    ADD CONSTRAINT fkskn137mklcyckq004wx39y7nq FOREIGN KEY (pipeline_run_id) REFERENCES public.pipeline_runs(id);


--
-- Name: staging_transactions fkslx9va6qxquldopje2y2ucgdm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staging_transactions
    ADD CONSTRAINT fkslx9va6qxquldopje2y2ucgdm FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id);


--
-- Name: rejected_transactions fkt3d34wr90y68v7biggo59fiqm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rejected_transactions
    ADD CONSTRAINT fkt3d34wr90y68v7biggo59fiqm FOREIGN KEY (staging_transaction_id) REFERENCES public.staging_transactions(id);


--
-- Name: dead_letter_transactions fktage6m8cqec50pmpy0fjjikpq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dead_letter_transactions
    ADD CONSTRAINT fktage6m8cqec50pmpy0fjjikpq FOREIGN KEY (ingestion_run_id) REFERENCES public.ingestion_runs(id);


--
-- Name: investigation_cases fku7ssrrlfttlqp1a86ayxis7g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investigation_cases
    ADD CONSTRAINT fku7ssrrlfttlqp1a86ayxis7g FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- PostgreSQL database dump complete
--

