-- Adds columns/table introduced by the auth-hardening and idempotency-key work, on top of the
-- V1 baseline snapshot (which predates them).

ALTER TABLE app_users
    ADD COLUMN failed_login_attempts integer NOT NULL DEFAULT 0,
    ADD COLUMN token_version integer NOT NULL DEFAULT 0;

-- Widened to fit base64-encoded AES-GCM ciphertext once PII_ENCRYPTION_KEY is set (see
-- common/crypto/*Converter) - a no-op in length terms while encryption stays disabled (blank key).
ALTER TABLE customers
    ALTER COLUMN email TYPE varchar(500),
    ALTER COLUMN phone TYPE varchar(500);

ALTER TABLE banking_transactions
    ALTER COLUMN device_id TYPE varchar(500),
    ALTER COLUMN ip_address TYPE varchar(500);

ALTER TABLE app_users
    ALTER COLUMN email TYPE varchar(500);

CREATE TABLE idempotency_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key character varying(255) NOT NULL,
    endpoint character varying(255) NOT NULL,
    resource_id character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT uk_idempotency_key_endpoint UNIQUE (idempotency_key, endpoint)
);
