CREATE TABLE fraud_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id character varying(255) NOT NULL UNIQUE,
    rule_code character varying(255) NOT NULL UNIQUE,
    name character varying(255) NOT NULL,
    description character varying(255),
    category character varying(255),
    enabled boolean NOT NULL,
    threshold_value character varying(255),
    secondary_threshold_value character varying(255),
    score_impact integer NOT NULL,
    secondary_score_impact integer,
    severity character varying(255) NOT NULL,
    rule_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(255)
);

CREATE TABLE fraud_rule_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id character varying(255) NOT NULL,
    version_number integer NOT NULL,
    old_config_json text,
    new_config_json text NOT NULL,
    changed_by character varying(255) NOT NULL,
    change_reason character varying(255),
    created_at timestamp(6) without time zone NOT NULL
);

CREATE INDEX idx_fraud_rule_versions_rule_id ON fraud_rule_versions (rule_id);
