CREATE TABLE case_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id character varying(255) NOT NULL UNIQUE,
    case_id character varying(255) NOT NULL,
    author_username character varying(255) NOT NULL,
    author_role character varying(255),
    note_text text NOT NULL,
    internal_only boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_case_notes_case_id ON case_notes (case_id);

CREATE TABLE case_timeline_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id character varying(255) NOT NULL UNIQUE,
    case_id character varying(255) NOT NULL,
    event_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    actor_username character varying(255),
    actor_role character varying(255),
    metadata_json text,
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_case_timeline_events_case_id ON case_timeline_events (case_id);

CREATE TABLE case_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id character varying(255) NOT NULL,
    old_status character varying(255) NOT NULL,
    new_status character varying(255) NOT NULL,
    changed_by character varying(255) NOT NULL,
    reason character varying(255),
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_case_status_history_case_id ON case_status_history (case_id);
