CREATE TABLE alert_sla_policies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id character varying(255) NOT NULL UNIQUE,
    priority character varying(255) NOT NULL UNIQUE,
    response_time_minutes integer NOT NULL,
    resolution_time_minutes integer NOT NULL,
    enabled boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);

CREATE TABLE alert_sla_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id character varying(255) NOT NULL UNIQUE,
    policy_id character varying(255) NOT NULL,
    response_deadline timestamp(6) without time zone NOT NULL,
    resolution_deadline timestamp(6) without time zone NOT NULL,
    first_acknowledged_at timestamp(6) without time zone,
    resolved_at timestamp(6) without time zone,
    response_breached boolean NOT NULL,
    resolution_breached boolean NOT NULL,
    status character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_alert_sla_results_status ON alert_sla_results (status);

CREATE TABLE alert_escalations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    escalation_id character varying(255) NOT NULL UNIQUE,
    alert_id character varying(255) NOT NULL,
    escalated_from character varying(255) NOT NULL,
    escalated_to character varying(255) NOT NULL,
    reason character varying(255),
    escalation_level integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_alert_escalations_alert_id ON alert_escalations (alert_id);

CREATE TABLE alert_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id character varying(255) NOT NULL,
    old_status character varying(255) NOT NULL,
    new_status character varying(255) NOT NULL,
    changed_by character varying(255) NOT NULL,
    reason character varying(255),
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_alert_status_history_alert_id ON alert_status_history (alert_id);
