CREATE TABLE streaming_event_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id character varying(255) NOT NULL,
    topic character varying(255) NOT NULL,
    event_type character varying(255) NOT NULL,
    transaction_id character varying(255),
    status character varying(255) NOT NULL,
    message text,
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_streaming_event_logs_created_at ON streaming_event_logs (created_at);

CREATE TABLE streaming_metrics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_date date NOT NULL UNIQUE,
    events_produced bigint NOT NULL,
    events_consumed bigint NOT NULL,
    events_failed bigint NOT NULL,
    alerts_generated bigint NOT NULL,
    average_processing_latency_ms double precision NOT NULL,
    last_event_at timestamp(6) without time zone
);

CREATE TABLE streaming_dead_letter_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id character varying(255) NOT NULL UNIQUE,
    source_topic character varying(255) NOT NULL,
    raw_payload text NOT NULL,
    error_reason character varying(255) NOT NULL,
    error_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);
