-- customers_status_check (from V1) hardcodes ACTIVE/SUSPENDED/CLOSED and would reject the new
-- LOCKED value the same way audit_logs_event_type_check rejected new AuditEventType values (see
-- V7) - drop it for the same reason, consistent with the rest of the schema, which doesn't mirror
-- Java enums with DB CHECK constraints.
ALTER TABLE customers DROP CONSTRAINT IF EXISTS customers_status_check;

CREATE TABLE customer_lock_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lock_request_id character varying(255) NOT NULL UNIQUE,
    customer_id bigint NOT NULL REFERENCES customers (id),
    requested_by character varying(255) NOT NULL,
    requested_by_role character varying(255) NOT NULL,
    reason character varying(255),
    status character varying(255) NOT NULL,
    reviewed_by character varying(255),
    reviewed_at timestamp(6) without time zone,
    review_notes character varying(255),
    created_at timestamp(6) without time zone NOT NULL
);
CREATE INDEX idx_customer_lock_requests_customer_id ON customer_lock_requests (customer_id);
CREATE INDEX idx_customer_lock_requests_status ON customer_lock_requests (status);
