export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8080";

export const ML_SERVICE_URL =
  process.env.NEXT_PUBLIC_ML_SERVICE_URL ?? "http://localhost:8000";

export const endpoints = {
  customers: `${API_BASE_URL}/api/v1/customers`,
  customerRiskProfile: (customerId: string) => `${API_BASE_URL}/api/v1/customers/${customerId}/risk-profile`,
  customerLock: (customerId: string) => `${API_BASE_URL}/api/v1/customers/${customerId}/lock`,
  customerUnlock: (customerId: string) => `${API_BASE_URL}/api/v1/customers/${customerId}/unlock`,
  customerLockRequests: (customerId: string) => `${API_BASE_URL}/api/v1/customers/${customerId}/lock-requests`,
  linkedCustomers: (customerId: string) => `${API_BASE_URL}/api/v1/customers/${customerId}/linked-customers`,
  lockRequestApprove: (lockRequestId: string) => `${API_BASE_URL}/api/v1/customers/lock-requests/${lockRequestId}/approve`,
  lockRequestReject: (lockRequestId: string) => `${API_BASE_URL}/api/v1/customers/lock-requests/${lockRequestId}/reject`,
  pendingLockRequests: `${API_BASE_URL}/api/v1/customers/lock-requests/pending`,
  accounts: `${API_BASE_URL}/api/v1/accounts`,
  transactions: `${API_BASE_URL}/api/v1/transactions`,
  riskScores: `${API_BASE_URL}/api/v1/risk-scores`,
  alerts: `${API_BASE_URL}/api/v1/alerts`,
  alertStatus: (alertId: string) => `${API_BASE_URL}/api/v1/alerts/${alertId}/status`,
  alertAssign: (alertId: string) => `${API_BASE_URL}/api/v1/alerts/${alertId}/assign`,
  cases: `${API_BASE_URL}/api/v1/cases`,
  caseById: (caseId: string) => `${API_BASE_URL}/api/v1/cases/${caseId}`,
  caseDecision: (caseId: string) => `${API_BASE_URL}/api/v1/cases/${caseId}/decision`,
  auditLogs: `${API_BASE_URL}/api/v1/audit-logs`,
  pipelineRuns: `${API_BASE_URL}/api/v1/pipelines/runs`,
  pipelineMetrics: `${API_BASE_URL}/api/v1/pipelines/metrics`,
  pipelineErrors: `${API_BASE_URL}/api/v1/pipelines/errors`,
  dataQualityRuns: `${API_BASE_URL}/api/v1/data-quality/runs`,
  dataQualityResults: `${API_BASE_URL}/api/v1/data-quality/results`,
  dataQualityIssues: `${API_BASE_URL}/api/v1/data-quality/issues`,
  ingestionUpload: `${API_BASE_URL}/api/v1/ingestion/upload`,
  ingestionRuns: `${API_BASE_URL}/api/v1/ingestion/runs`,
  rejectedRecords: `${API_BASE_URL}/api/v1/ingestion/rejected-records`,
  deadLetterTransactions: `${API_BASE_URL}/api/v1/dead-letter/transactions`,
  deadLetterRetry: (id: string) => `${API_BASE_URL}/api/v1/dead-letter/transactions/${id}/retry`,
  deadLetterIgnore: (id: string) => `${API_BASE_URL}/api/v1/dead-letter/transactions/${id}/ignore`,

  mlHealth: `${ML_SERVICE_URL}/health`,
  mlModelInfo: `${ML_SERVICE_URL}/api/v1/model-info`,
  mlScore: `${ML_SERVICE_URL}/api/v1/score`,
  mlMonitoringSummary: `${ML_SERVICE_URL}/api/v1/monitoring/summary`,
  mlMonitoringPredictions: `${ML_SERVICE_URL}/api/v1/monitoring/predictions`,
  mlMonitoringScoreDistribution: `${ML_SERVICE_URL}/api/v1/monitoring/score-distribution`,
  mlMonitoringDrift: `${ML_SERVICE_URL}/api/v1/monitoring/drift`,
  mlMonitoringRetrainingHistory: `${ML_SERVICE_URL}/api/v1/monitoring/retraining-history`,

  login: `${API_BASE_URL}/api/v1/auth/login`,
  me: `${API_BASE_URL}/api/v1/auth/me`,
  users: `${API_BASE_URL}/api/v1/users`,
  assignableUsers: `${API_BASE_URL}/api/v1/directory/assignable-users`,
  userById: (userId: string) => `${API_BASE_URL}/api/v1/users/${userId}`,
  userStatus: (userId: string) => `${API_BASE_URL}/api/v1/users/${userId}/status`,
  userResetPassword: (userId: string) => `${API_BASE_URL}/api/v1/users/${userId}/reset-password`,
  testTransactions: `${API_BASE_URL}/api/v1/test-transactions`,

  fraudRules: `${API_BASE_URL}/api/v1/fraud-rules`,
  fraudRuleById: (ruleId: string) => `${API_BASE_URL}/api/v1/fraud-rules/${ruleId}`,
  fraudRuleEnable: (ruleId: string) => `${API_BASE_URL}/api/v1/fraud-rules/${ruleId}/enable`,
  fraudRuleDisable: (ruleId: string) => `${API_BASE_URL}/api/v1/fraud-rules/${ruleId}/disable`,
  fraudRuleVersions: (ruleId: string) => `${API_BASE_URL}/api/v1/fraud-rules/${ruleId}/versions`,

  caseTimeline: (caseId: string) => `${API_BASE_URL}/api/v1/cases/${caseId}/timeline`,
  caseNotes: (caseId: string) => `${API_BASE_URL}/api/v1/cases/${caseId}/notes`,
  caseNoteById: (caseId: string, noteId: string) => `${API_BASE_URL}/api/v1/cases/${caseId}/notes/${noteId}`,
  caseStatusHistory: (caseId: string) => `${API_BASE_URL}/api/v1/cases/${caseId}/status-history`,

  slaSummary: `${API_BASE_URL}/api/v1/sla/summary`,
  slaAlerts: `${API_BASE_URL}/api/v1/sla/alerts`,
  slaBreached: `${API_BASE_URL}/api/v1/sla/breached`,
  slaNearBreach: `${API_BASE_URL}/api/v1/sla/near-breach`,
  slaPolicies: `${API_BASE_URL}/api/v1/sla/policies`,
  slaPolicyById: (policyId: string) => `${API_BASE_URL}/api/v1/sla/policies/${policyId}`,
  alertEscalate: (alertId: string) => `${API_BASE_URL}/api/v1/alerts/${alertId}/escalate`,
  alertBulkAssign: `${API_BASE_URL}/api/v1/alerts/bulk-assign`,
  alertBulkEscalate: `${API_BASE_URL}/api/v1/alerts/bulk-escalate`,
  alertBulkStatus: `${API_BASE_URL}/api/v1/alerts/bulk-status`,
  caseBulkUpdate: `${API_BASE_URL}/api/v1/cases/bulk-update`,
  notifications: (since?: string) =>
    `${API_BASE_URL}/api/v1/notifications${since ? `?since=${encodeURIComponent(since)}` : ""}`,
  analyticsSummary: `${API_BASE_URL}/api/v1/analytics/summary`,
  alertStatusHistory: (alertId: string) => `${API_BASE_URL}/api/v1/alerts/${alertId}/status-history`,
  alertEscalations: (alertId: string) => `${API_BASE_URL}/api/v1/alerts/${alertId}/escalations`,

  streamingPublish: `${API_BASE_URL}/api/v1/streaming/transactions/publish`,
  streamingMetrics: `${API_BASE_URL}/api/v1/streaming/metrics`,
  streamingEvents: `${API_BASE_URL}/api/v1/streaming/events`,
  streamingDeadLetterEvents: `${API_BASE_URL}/api/v1/streaming/dead-letter-events`,
  streamingDeadLetterRetry: (eventId: string) => `${API_BASE_URL}/api/v1/streaming/dead-letter-events/${eventId}/retry`,
  streamingDeadLetterIgnore: (eventId: string) => `${API_BASE_URL}/api/v1/streaming/dead-letter-events/${eventId}/ignore`,
};
